config/routes.rb
Hazifeladat::Application.routes.draw do
  resources :comments

  resources :blogposts

  resources :proiects

  resources :users

  resources :events

  root :to => 'proiects#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :name, :on => :create,
                        :message => 'cannot be empty'
  validates_uniqueness_of :name, :on => :create,
                        :message => 'already exists. Please choose another one'
  has_and_belongs_to_many :proiects#,
                          #:class_name => "User",
                          #:join_table => "proiects_users", 
                          #:foreign_key => "proiect_id"
  has_and_belongs_to_many :events#,
                          #:class_name => "user", 
                          #:join_table => "events_users", 
                          #:foreign_key => "event_id"
  has_many :blogposts
  has_many :comments
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :name %>
    <%= f.association :proiects %>
    <%= f.association :events %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Projects in</th>
    <th>Events in</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= "---- (" << user.proiects.count.to_s() << ") ----" %></td>
    <td><%= "---- (" << user.events.count.to_s() << ") ----" %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Involved in projects:</b>
  <ul>
  	<% @user.proiects.each do |proiect| %>
  		<li><%= link_to proiect.title, proiect_path(proiect) %></li>
  	<% end %>
  </ul>
</p>

<p>
  <b>Participating at events:</b>
  <ul>
  	<% @user.events.each do |event| %>
  		<li><%= link_to event.title, event_path(event) %></li>
  	<% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>