config/routes.rb
Hazifeladat::Application.routes.draw do
  resources :comments

  resources :blogposts

  resources :proiects

  resources :users

  resources :events

  root :to => 'proiects#index'

end

app/models/proiect.rb
class Proiect < ActiveRecord::Base
  validates_length_of :title, :minimum =>  8, :on => :create, 
                      :message => 'must be at least 8 characters long'
  validates_length_of :description, :minimum => 20, :on => :create, 
                      :message => 'must be at least 20 characters long'
  has_and_belongs_to_many :users#, 
                          #:class_name => "Proiect",
                          #:join_table => "proiects_users", 
                          #:foreign_key => "user_id"
  has_many :events
  has_many :blogposts
  has_many :comments
end

app/controllers/proiects_controller.rb
class ProiectsController < ApplicationController
  # GET /proiects
  # GET /proiects.json
  respond_to :mobile
  respond_to :html
  respond_to :json

  def index
    @proiects = Proiect.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proiects }
      format.mobile
    end
  end

  # GET /proiects/1
  # GET /proiects/1.json
  def show
    @proiect = Proiect.find(params[:id])
  end

  # GET /proiects/new
  # GET /proiects/new.json
  def new
    @proiect = Proiect.new
  end

  # GET /proiects/1/edit
  def edit
    @proiect = Proiect.find(params[:id])
  end

  # POST /proiects
  # POST /proiects.json
  def create
    @proiect = Proiect.new(params[:proiect])

    respond_to do |format|
      if @proiect.save
        format.html { redirect_to @proiect, notice: 'Proiect was successfully created.' }
        format.json { render json: @proiect, status: :created, location: @proiect }
        format.mobile { redirect_to @proiect, notice: 'Proiect was successfully created.' }
      else
        format.html { render action: "new" }
        format.json { render json: @proiect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proiects/1
  # PUT /proiects/1.json
  def update
    @proiect = Proiect.find(params[:id])

    respond_to do |format|
      if @proiect.update_attributes(params[:proiect])
        format.html { redirect_to @proiect, notice: 'Proiect was successfully updated.' }
        format.json { head :ok }
        format.mobile { redirect_to @proiect, notice: 'Proiect was successfully updated.' }
      else
        format.html { render action: "edit" }
        format.json { render json: @proiect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proiects/1
  # DELETE /proiects/1.json
  def destroy
    @proiect = Proiect.find(params[:id])
    @proiect.destroy

    respond_to do |format|
      format.html { redirect_to proiects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/proiects_helper.rb
module ProiectsHelper
end

app/views/proiects/_form.html.erb
<%= simple_form_for(@proiect) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :title %>
    <%= f.input :description %>
	<%= f.association :users %>

  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/proiects/_form.mobile.haml
#forms
  = simple_form_for(@proiect) do |f|
    = f.error_notification
    %ul.edit.rounded
      %li= f.input :title
      %li= f.input :description
      %li= f.association :users
    %a.submit.blueButton.new_project{ :href => '#' } Submit

app/views/proiects/edit.html.erb
<h1>Editing proiect</h1>

<%= render 'form' %>

<%= link_to 'Show', @proiect %> |
<%= link_to 'Back', proiects_path %>

app/views/proiects/edit.mobile.haml
%div{ :id => "projectsedit#{@proiect.id}"}
  .toolbar
    = link_to "Cancel", "#", :class => "back"
    %h1= "Edit #{@proiect.title}"
  .content
    = render 'form'

app/views/proiects/index.html.erb
<h1>Listing proiects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Participants</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proiects.each do |proiect| %>
  <tr>
    <td><%= proiect.title %></td>
    <td>
    	<%= proiect.description.to_s()[0..20] << "..." %>
	</td>
    <td><%= "---- (" << proiect.users.count.to_s() << ") ----" %></td>
    <td><%= link_to 'Show', proiect %></td>
    <td><%= link_to 'Edit', edit_proiect_path(proiect) %></td>
    <td><%= link_to 'Destroy', proiect, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proiect', new_proiect_path %>

app/views/proiects/index.mobile.haml
!!! XML
!!!
%html
  %head
    %title= h(yield(:title) || "Hazifeladat")
    = stylesheet_link_tag "/jqtouch/jqtouch.css", "/jqtouch/themes/apple/theme.css"
    = javascript_include_tag "/jqtouch/jquery.min.js", "/jqtouch/jqtouch.js", "mobile"
    = stylesheet_link_tag 'mobile' if mobile_device?
    = csrf_meta_tags

  %body
    #jqt
      #main
        .toolbar
          %h1 Project management

        - unless flash.empty?
          .info
            - flash.each do |name, msg|
              = content_tag :div, msg, :id => "flash_#{name}"
        %ul
          - for project in @proiects
            %li.arrow
              = link_to project.title, project
        %ul
          %li.arrow
            = link_to "New Project", new_proiect_path
    
        .info
          maximus 

app/views/proiects/new.html.erb
<h1>New proiect</h1>

<%= render 'form' %>

<%= link_to 'Back', proiects_path %>

app/views/proiects/new.mobile.haml
%div{ :id => "projectsnew"}
  .toolbar
    = link_to "Back", "#", :class => "back"
    %h1 New project
  .content
    = render 'form'

app/views/proiects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @proiect.title %>
</p>

<p>
  <b>Description:</b>
  <%= @proiect.description %>
</p>

<p>
  <b>Participants:</b>
  <ul>
  <% @proiect.users.each do |user| %>
    <li><%= link_to user.name, user_url(user)%></li>
  <% end  %>
  </ul>
</p>

<div class="actions">
  <%= link_to 'Edit', edit_proiect_path(@proiect) %> |
</div>

app/views/proiects/show.mobile.haml
%div{ :id => "projects#{@proiect.id}" }
  .toolbar
    = link_to "Back", "#{proiects_path}", :class => "back"
    %h1= @proiect.title
    %a.button{ :href =>"#{edit_proiect_path(@project)}"} Edit
  .content
    %h1 Description
    %p
      = @proiect.description
    %h2 Participants:
    %ul
      - @proiect.users.each do |user|
        %li= link_to user.name, user_url(user)